In [2]:
# Dependencies
import pandas as pd
import requests
import json
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as sts
import csv
import seaborn as sns
from collections import Counter

import statistics as stats

from numpy.random import seed

import seaborn as sns; sns.set()

import os

import warnings

In [3]:
# Read application_data csv file
# Create application DataFrame

legislative_data = "Resources/legislators-historical.csv"
legislative_df = pd.read_csv(legislative_data)
legislative_df.head()

,last_name,first_name,middle_name,suffix,nickname,full_name,birthday,gender,type,state,...,opensecrets_id,lis_id,fec_ids,cspan_id,govtrack_id,votesmart_id,ballotpedia_id,washington_post_id,icpsr_id,wikipedia_id
0,Bassett,Richard,NaN,NaN,NaN,NaN,1745-04-02,M,sen,DE,...,NaN,NaN,NaN,NaN,401222,NaN,NaN,NaN,507.0,Richard Bassett (politician)
1,Bland,Theodorick,NaN,NaN,NaN,NaN,1742-03-21,M,rep,VA,...,NaN,NaN,NaN,NaN,401521,NaN,NaN,NaN,786.0,Theodorick Bland (congressman)
2,Burke,Aedanus,NaN,NaN,NaN,NaN,1743-06-16,M,rep,SC,...,NaN,NaN,NaN,NaN,402032,NaN,NaN,NaN,1260.0,Aedanus Burke
3,Carroll,Daniel,NaN,NaN,NaN,NaN,1730-07-22,M,rep,MD,...,NaN,NaN,NaN,NaN,402334,NaN,NaN,NaN,1538.0,Daniel Carroll
4,Clymer,George,NaN,NaN,NaN,NaN,1739-03-16,M,rep,PA,...,NaN,NaN,NaN,NaN,402671,NaN,NaN,NaN,1859.0,George Clymer

In [4]:
list(legislative_df.columns.values)

['last_name',
 'first_name',
 'middle_name',
 'suffix',
 'nickname',
 'full_name',
 'birthday',
 'gender',
 'type',
 'state',
 'district',
 'senate_class',
 'party',
 'url',
 'address',
 'phone',
 'contact_form',
 'rss_url',
 'twitter',
 'facebook',
 'youtube',
 'youtube_id',
 'bioguide_id',
 'thomas_id',
 'opensecrets_id',
 'lis_id',
 'fec_ids',
 'cspan_id',
 'govtrack_id',
 'votesmart_id',
 'ballotpedia_id',
 'washington_post_id',
 'icpsr_id',
 'wikipedia_id']

In [5]:
legislative_df.drop(['url','address',
 'phone',
 'contact_form',
 'rss_url',
 'twitter',
 'facebook',
 'youtube',
 'youtube_id',
 'bioguide_id',
 'thomas_id',
 'opensecrets_id',
 'lis_id',
 'fec_ids',
 'cspan_id',
 'govtrack_id',
 'votesmart_id',
 'ballotpedia_id',
 'washington_post_id',
 'icpsr_id',
 'wikipedia_id'], axis=1, inplace=True)

In [6]:
legislative_df.drop([
 'nickname',
 'birthday',], axis=1, inplace=True)

In [7]:
list(legislative_df.columns.values)

['last_name',
 'first_name',
 'middle_name',
 'suffix',
 'full_name',
 'gender',
 'type',
 'state',
 'district',
 'senate_class',
 'party']

In [ ]:
clean_appdata = appdata.rename(columns={"LAST NAME": "last_name",
                                        "FIRST NAME": "first_name",
                                        "MIDDLE NAME": "middle_name,
                                        "SUFFIX": "suffix",
                                        "FULL NAME": "full_name",
                                        "GENDER": "gender",
                                        "CONGRESSIONAL BRANCH": "type",